- name: Web Design
  description: "Beautiful, user-focused website design."
- name: Web Development
  description: "Robust, scalable web development solutions."
- name: Branding
  description: "Brand identity, logo, and visual design." 